"""add payout destination and method

Revision ID: f9846adf42ca
Revises: 'fb21b284a104'
Create Date: 2026-10-03 12:48:21.406121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9846adf42ca'
down_revision: Union[str, None] = 'fb21b284a104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payout_requests', sa.Column('method', sa.String(), nullable=True))
    op.add_column('payout_requests', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('payout_requests', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payout_requests', 'processed_at')
    op.drop_column('payout_requests', 'destination')
    op.drop_column('payout_requests', 'method')
    # ### end Alembic commands ###
